const SERVICE_FTTC_BROADBAND = 'FTTC Broadband';
const SERVICE_FTTP_BROADBAND = 'FTTP Broadband';
const SERVICE_MOBILE = 'LTE';
const SERVICE_NETWORK = 'NETWORK';
const STATUS_CONNECTED = 'Connected';
const STATUS_DISCONNECTED = 'Disconnected';
const STATUS_DOWN = 'DOWN';
const STATUS_STANDBY = 'Standby';
const STATUS_UNKNOWN = 'Unknown';
const STATUS_UP = 'UP';
const LOGS_UPLOADED_MESSAGE = 'Logs uploaded';

module.exports = {
  SERVICE_FTTC_BROADBAND,
  SERVICE_FTTP_BROADBAND,
  SERVICE_MOBILE,
  SERVICE_NETWORK,
  STATUS_CONNECTED,
  STATUS_DISCONNECTED,
  STATUS_DOWN,
  STATUS_STANDBY,
  STATUS_UNKNOWN,
  STATUS_UP,
  LOGS_UPLOADED_MESSAGE,
};
